# Generated by Django 3.2 on 2023-01-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, help_text='Укажите номер телефона', null=True, verbose_name='Телефон'),
        ),
    ]
